### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by teinhonglo** [Ardavans/sHDP#5]
Hello, this is a great project!
I have some questions to ask you, I am download your code, and then implement the following problems, may I ask what be the reason?

D{'Nmax': 40, 'tau': 0.8, 'mbsize': 10.0, 'infSeed': 1, 'dataset': 'nipsD', 'alpha': 1.0, 'kappa_sgd': 0.6, 'gamma': 2.0}
Traceback (most recent call last):
  File "./runner.py", line 225, in <module>
    HDPRunner(args)
  File "./runner.py", line 41, in HDPRunner
    temp_file = open(project_path+'data/'+datasetname+'/texts.pk', 'rb')
IOError: [Errno 2] No such file or directory: 'data/nipsD/texts.pk'

**Comment by Ardavans** [comment]
Hi there,

Thank you! Glad you are enjoying it :)

I just tried the code again and it seems that it's working. Can you try
cloning the code in a clean directory and then running the following
command:

./runner.py -is 1 -alpha 1 -gamma 2 -Nmax 40 -kappa_sgd 0.6 -tau 0.8
-mbsize 10 -dataset nips
Let me know if this works and if not what is the error.

Thank you,
Ardavan
